version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    env_file:
      - app.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Salman12@
        MYSQL_DATABASE: blogdb
        MYSQL_ROOT_HOST: '%'
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_server:
    build: 
     context: .
    container_name: blog
    ports:
      - 8080:8080
    env_file:
      - app.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    environment:
      - DBIP=mysql:3306

networks:
  backend:
   driver: bridge

volumes:
  mysql-data: